#!/usr/bin/env python3
"""Factor numbers """
import sys

def read_numbers_from_file(file_name):
	"""Read numbers from file and return a list"""
	with open(file_name, "r", encodeing="utf-8") as file:
		lines = file.readlines()
	numbers_to_factor = [int(line) for line in lines]
	return numbers_to_factor

def factorize_number(n):
	"""Factorize a given number and print the result"""
	for factor in range(1, n):
		if n == (n // factor) * factor:
			print("{}={}*{}".format(n, (n // factor), factor))
			break

def factorize_list(numbers):
	"""Factorize each number in the given list"""
	for num in numbers:
		factorize_number(num)

if __name__ == "__main__":
	if len(sys.argv) == 2:
		numbers_to_factorize = read_numbers_from_file(sys.argv[1])
		factorize_list(numbers_to_factorize)
	else:
		print("Usage: {} <file>".format(sys.argv[0]))
		sys.exit(1)
